language: ruby
#cache: bundler
rvm:
    - 2.1.5
script: rake ci
compiler:
    - gcc # for ctags
before_install:
    - sudo apt-get install vim-gtk
    - git clone https://github.com/universal-ctags/ctags.git
    - (cd ctags && autoreconf -f -i -v && ./configure --prefix="$HOME" && make -j 4 install)
before_script:
    - "export DISPLAY=:99.0"
    - "export PATH=$PATH:$HOME/bin"
    - "sh -e /etc/init.d/xvfb start"
